[tools]
go = "1.26.0"
lua = "latest"
# node.postinstall = "command -v corepack >/dev/null || npm install -g npm; npm install -g -y corepack && corepack enable pnpm"
node.version = "lts"
python = "latest"
usage = "latest"

[hooks]
enter = "mise install --quiet"

[settings]
experimental = true
jobs = 8
# trusted_config_paths = [
#   '~/work/my-trusted-projects',
# ]

# [shell_alias]
# ll = "ls -la"
